"""
Trading signal models.
Represents buy/sell signals generated by strategies.
"""
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Optional


class SignalType(Enum):
    """Types of trading signals."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    STRONG_BUY = "strong_buy"  # For tiered strategies
    CLOSE = "close"


class SignalStrength(Enum):
    """Signal confidence levels."""
    WEAK = 1
    MODERATE = 2
    STRONG = 3
    VERY_STRONG = 4


@dataclass
class TradingSignal:
    """
    Represents a trading signal with all relevant context.
    """
    timestamp: datetime
    symbol: str
    signal_type: SignalType
    strength: SignalStrength
    price: Decimal
    
    # Strategy context
    strategy_name: str
    reason: str  # Human-readable explanation
    
    # Position sizing recommendation
    recommended_position_size: Optional[Decimal] = None  # As percentage (0.0 to 1.0)
    
    # Technical indicators that triggered this signal
    indicators: dict[str, float] = None
    
    # Risk management
    stop_loss: Optional[Decimal] = None
    take_profit: Optional[Decimal] = None
    
    def __post_init__(self):
        if self.indicators is None:
            self.indicators = {}
        
        if self.recommended_position_size is not None:
            if not 0 <= self.recommended_position_size <= 1:
                raise ValueError("Position size must be between 0 and 1")
    
    def __str__(self) -> str:
        return (f"{self.signal_type.value.upper()} signal for {self.symbol} "
                f"at {self.price} - {self.reason}")
    
    @property
    def is_entry_signal(self) -> bool:
        """Check if this is an entry signal."""
        return self.signal_type in [SignalType.BUY, SignalType.STRONG_BUY]
    
    @property
    def is_exit_signal(self) -> bool:
        """Check if this is an exit signal."""
        return self.signal_type in [SignalType.SELL, SignalType.CLOSE]


@dataclass
class SignalHistory:
    """
    Collection of trading signals for analysis and backtesting.
    """
    signals: list[TradingSignal]
    
    def __len__(self) -> int:
        return len(self.signals)
    
    def add_signal(self, signal: TradingSignal) -> None:
        """Add a new signal to the history."""
        self.signals.append(signal)
    
    def get_signals_by_type(self, signal_type: SignalType) -> list[TradingSignal]:
        """Filter signals by type."""
        return [s for s in self.signals if s.signal_type == signal_type]
    
    def get_latest(self, n: int = 1) -> list[TradingSignal]:
        """Get the most recent n signals."""
        return self.signals[-n:] if n <= len(self.signals) else self.signals
